### ISSUE TITLE
Will not build

### ISSUE THREAD

**Issue by qodeshi** [alwaysdoingstuff/timelinetest#1]
Hi. 

I'm having issues building this. Maybe that's intentional? Only reason I'm asking is because I'd be interested in helping or contributing in some way. I'm genuinely curious. Sorry if this seems intrusive.

**Comment by alwaysdoingstuff** [comment]
Sorry for the delayed response. 

This GIT does not build on purpose. This is only a testing repo, and it is missing the file for the blockchain parameters. I'm planning on uploading the final code and switching over to the proper branch sometime in the next week or two. I'm attempting to prevent any sort of pre-mining and having people capitalize on the coin. This project is meant to be a tool of self-exploration, and not a market to corner. Keep watching.
